/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Database.DatabaseConnection;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;

/**
 *
 * @author abhilashkumargorle
 */
public class LandingJPanel extends javax.swing.JPanel {
    
    private MainJFrame mainframe;

    /**
     * Creates new form LandingJPanel
     */
    public LandingJPanel(MainJFrame mainframe) {
        this.mainframe = mainframe;
        initComponents();
         displayTotalDonationAmount();
        
    }
    
    
private void displayTotalDonationAmount() {
    try {
        Connection connection = (Connection) DatabaseConnection.getConnection();
        String sql = "SELECT SUM(CAST(amount AS DECIMAL(10, 2))) AS total_donation FROM donations";
        PreparedStatement preparedStatement = connection.prepareStatement(sql);

        ResultSet resultSet = preparedStatement.executeQuery();

        if (resultSet.next()) {
            String totalDonation = resultSet.getString("total_donation");
            txtDonate.setText(totalDonation);
            System.out.println(totalDonation);
        }
       
        resultSet.close();
        preparedStatement.close();
        // Close the connection if needed

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error retrieving total donation amount.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warningMsg = new javax.swing.JLabel();
        action = new javax.swing.JLabel();
        btnDonate = new javax.swing.JButton();
        txtDonate = new javax.swing.JTextField();
        lblDollar = new javax.swing.JLabel();
        earth = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(969, 407));

        warningMsg.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        warningMsg.setForeground(new java.awt.Color(255, 255, 255));
        warningMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningMsg.setText("An online university for those who are on the move");

        action.setFont(new java.awt.Font("Segoe UI Black", 1, 34)); // NOI18N
        action.setForeground(new java.awt.Color(255, 255, 255));
        action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        action.setText("Welcome to OpenMind!");

        btnDonate.setBackground(new java.awt.Color(153, 255, 153));
        btnDonate.setFont(new java.awt.Font("Segoe UI Variable", 1, 10)); // NOI18N
        btnDonate.setForeground(new java.awt.Color(0, 102, 102));
        btnDonate.setText("DONATE");
        btnDonate.setBorder(null);
        btnDonate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateActionPerformed(evt);
            }
        });

        txtDonate.setEditable(false);
        txtDonate.setBackground(new java.awt.Color(0, 0, 0));
        txtDonate.setFont(new java.awt.Font("Segoe UI Black", 1, 21)); // NOI18N
        txtDonate.setForeground(new java.awt.Color(255, 255, 255));
        txtDonate.setBorder(null);
        txtDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonateActionPerformed(evt);
            }
        });

        lblDollar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblDollar.setForeground(new java.awt.Color(255, 255, 255));
        lblDollar.setText("$");

        earth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Earth.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("We heartly accept your generous donations!");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("___________________________________________________________________________________________________________________________________________________");

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Amount Collected :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warningMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(earth)
                    .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDollar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(action)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningMsg)
                .addGap(34, 34, 34)
                .addComponent(earth)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDollar)
                    .addComponent(txtDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDonate, txtDonate});

    }// </editor-fold>//GEN-END:initComponents

    private void btnDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateActionPerformed
        // TODO add your handling code here:

        DonateJPanel donate = new DonateJPanel(mainframe);
        mainframe.setRightComponent(donate);

    }//GEN-LAST:event_btnDonateActionPerformed

    private void txtDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action;
    private javax.swing.JButton btnDonate;
    private javax.swing.JLabel earth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDollar;
    private javax.swing.JTextField txtDonate;
    private javax.swing.JLabel warningMsg;
    // End of variables declaration//GEN-END:variables
}
