/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StudentWorkArea;

import ProfessorWorkArea.*;
import ui.MainJFrame;
import javax.swing.JOptionPane;
import Database.DatabaseConnection;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;



import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhinav Uni
 */
public class ViewStudentCourse extends javax.swing.JPanel {
    
    
    private String selectedNUID;
    MainJFrame mainframe;
    private String selectedCourse;

    /**
     * Creates new form CreateCourseJPanel
     */
    public ViewStudentCourse(MainJFrame mainframe,String selectedNUID,String selectedCourse) {
         this.mainframe = mainframe;
        this.selectedNUID = selectedNUID;
        this.selectedCourse = selectedCourse;
        initComponents();
        displayLecures();
        viewCourseDetails();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void displayLecures() {
        try {
            Connection connection = (Connection)DatabaseConnection.getConnection();
            Integer courseid = Integer.parseInt(selectedCourse);
            String sql = "SELECT lecturename, lecture_desc,  lecture_link ,lectureid FROM lectures WHERE courseid = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setInt(1, courseid);

            ResultSet resultSet = preparedStatement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblLectures.getModel();

            // Clear any existing rows in the table
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }

            // Add rows from the result set to the table
            while (resultSet.next()) {
                Vector<String> row = new Vector<>();
                row.add(resultSet.getString("lectureid"));
                row.add(resultSet.getString("lecturename"));
                row.add(resultSet.getString("lecture_desc"));
                row.add(resultSet.getString("lecture_link"));
                
                model.addRow(row);
            }

            resultSet.close();
            preparedStatement.close();
//            DatabaseConnection.closeConnection(connection);

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error retrieving course data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
      private void viewCourseDetails() {
//    String NUID = txtNUID.getText();
    
    try {
         Connection connection = (Connection)DatabaseConnection.getConnection();
//        selectedNUID = "1234567890";
        // Define the SQL query to retrieve user details based on NUID
        String sql = "SELECT courseid, nuid, coursename, course_desc, semester, year,region,language, projectname, reference_link, project_desc, require1, require2, require3, require4 FROM courses WHERE courseid = ?";
    
            // Create a PreparedStatement
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            // Bind the selectedNUID value to the placeholder
            preparedStatement.setString(1, selectedCourse);
            System.out.println(selectedCourse);
           

        ResultSet resultSet = preparedStatement.executeQuery();
//         System.out.println(resultSet.getString("Name") + "hello");
        if (resultSet.next()) {
            // Populate the text fields with retrieved data
        String CourseID = resultSet.getString("courseid");
        String retrievedCourseName = resultSet.getString("coursename");
        String retrievedCourseDesc = resultSet.getString("course_desc");
        String retrievedSemester = resultSet.getString("semester");
        int retrievedYear = resultSet.getInt("year");
        String retrievedRegion = resultSet.getString("region");
         String retrievedLanguage = resultSet.getString("language");
        String retrievedProjectName = resultSet.getString("projectname");
        String retrievedReferenceLink = resultSet.getString("reference_link");
        String retrievedProjectDesc = resultSet.getString("project_desc");
        String retrievedRequire1 = resultSet.getString("require1");
        String retrievedRequire2 = resultSet.getString("require2");
        String retrievedRequire3 = resultSet.getString("require3");
        String retrievedRequire4 = resultSet.getString("require4");

        // Now, populate your UI fields with the retrieved data
        txtCourseID.setText(String.valueOf(CourseID));
  
        txtCourseName.setText(retrievedCourseName);
        txtCourseDesc.setText(retrievedCourseDesc);
        txtSemester.setText(retrievedSemester);
        txtYear.setText(String.valueOf(retrievedYear));
        txtRegion.setText(retrievedRegion);
        txtLanguage.setText(retrievedLanguage);
        txtProjectName.setText(retrievedProjectName);
        txtProjectDesc.setText(retrievedProjectDesc);
        txtProjectReferences.setText(retrievedReferenceLink);
        txtProjectReq1.setText(retrievedRequire1);
        txtProjectReq2.setText(retrievedRequire2);
        txtProjectReq3.setText(retrievedRequire3);
        txtProjectReq4.setText(retrievedRequire4);
//        for (int i = 0; i < SemesterComboBox.getItemCount(); i++) {
//            String item = SemesterComboBox.getItemAt(i);
//            if (item.equals(retrievedSemester)) {
//                SemesterComboBox.setSelectedIndex(i);
//                break; // Exit the loop once a match is found
//            }
//        }

            
            
            // ... set the other fields similarly
        } else {
            System.out.println("User not found.");
        }

        resultSet.close();
        preparedStatement.close();
       
    } catch (SQLException e) {
        e.printStackTrace();
    }finally {
//        DatabaseConnection.closeConnection();
    }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        lblCourseDesc = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        txtCourseDesc = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        lblCourseName = new javax.swing.JLabel();
        lblCourseID = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        lblProjectName = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblProjectReferences = new javax.swing.JLabel();
        txtProjectReferences = new javax.swing.JTextField();
        txtProjectDesc = new javax.swing.JTextField();
        lblProjectDesc = new javax.swing.JLabel();
        lblProjectreq1 = new javax.swing.JLabel();
        txtProjectReq1 = new javax.swing.JTextField();
        lblProjectreq2 = new javax.swing.JLabel();
        txtProjectReq2 = new javax.swing.JTextField();
        lblProjectreq3 = new javax.swing.JLabel();
        txtProjectReq3 = new javax.swing.JTextField();
        lblProjectreq4 = new javax.swing.JLabel();
        txtProjectReq4 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblYear1 = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        txtLanguage = new javax.swing.JTextField();
        lblYear2 = new javax.swing.JLabel();
        Req1ComboBox = new javax.swing.JComboBox<>();
        Req2ComboBox = new javax.swing.JComboBox<>();
        Req3ComboBox = new javax.swing.JComboBox<>();
        Req4ComboBox = new javax.swing.JComboBox<>();
        txtSemester = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLectures = new javax.swing.JTable();
        btnViewLecture = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Lectures");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("My Course");

        txtCourseName.setEditable(false);
        txtCourseName.setBackground(new java.awt.Color(0, 0, 0));
        txtCourseName.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtCourseName.setForeground(new java.awt.Color(255, 255, 255));
        txtCourseName.setBorder(null);
        txtCourseName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCourseDesc.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblCourseDesc.setForeground(new java.awt.Color(153, 153, 153));
        lblCourseDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCourseDesc.setText("Course Desc :");

        lblYear.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblYear.setForeground(new java.awt.Color(153, 153, 153));
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear.setText("Year : ");

        lblSemester.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblSemester.setForeground(new java.awt.Color(153, 153, 153));
        lblSemester.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSemester.setText("Semester : ");

        txtCourseDesc.setEditable(false);
        txtCourseDesc.setBackground(new java.awt.Color(0, 0, 0));
        txtCourseDesc.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtCourseDesc.setForeground(new java.awt.Color(255, 255, 255));
        txtCourseDesc.setBorder(null);
        txtCourseDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtYear.setEditable(false);
        txtYear.setBackground(new java.awt.Color(0, 0, 0));
        txtYear.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtYear.setForeground(new java.awt.Color(255, 255, 255));
        txtYear.setBorder(null);
        txtYear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCourseName.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblCourseName.setForeground(new java.awt.Color(153, 153, 153));
        lblCourseName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCourseName.setText("Course Name : ");

        lblCourseID.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblCourseID.setForeground(new java.awt.Color(153, 153, 153));
        lblCourseID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCourseID.setText("Course ID : ");

        txtCourseID.setEditable(false);
        txtCourseID.setBackground(new java.awt.Color(0, 0, 0));
        txtCourseID.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtCourseID.setForeground(new java.awt.Color(255, 255, 255));
        txtCourseID.setBorder(null);
        txtCourseID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseIDActionPerformed(evt);
            }
        });

        lblProjectName.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectName.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectName.setText("Project Name: ");

        txtProjectName.setEditable(false);
        txtProjectName.setBackground(new java.awt.Color(0, 0, 0));
        txtProjectName.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectName.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectName.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add Final Project");

        lblProjectReferences.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectReferences.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectReferences.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectReferences.setText("References Link :");

        txtProjectReferences.setEditable(false);
        txtProjectReferences.setBackground(new java.awt.Color(0, 0, 0));
        txtProjectReferences.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReferences.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectReferences.setBorder(null);
        txtProjectReferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReferencesActionPerformed(evt);
            }
        });

        txtProjectDesc.setEditable(false);
        txtProjectDesc.setBackground(new java.awt.Color(0, 0, 0));
        txtProjectDesc.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectDesc.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectDesc.setBorder(null);
        txtProjectDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectDescActionPerformed(evt);
            }
        });

        lblProjectDesc.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectDesc.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectDesc.setText("Project Desc :");

        lblProjectreq1.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectreq1.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectreq1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectreq1.setText("Requirement 1:");

        txtProjectReq1.setEditable(false);
        txtProjectReq1.setBackground(new java.awt.Color(0, 0, 0));
        txtProjectReq1.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReq1.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectReq1.setBorder(null);
        txtProjectReq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReq1ActionPerformed(evt);
            }
        });

        lblProjectreq2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectreq2.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectreq2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectreq2.setText("Requirement 2 :");

        txtProjectReq2.setEditable(false);
        txtProjectReq2.setBackground(new java.awt.Color(0, 0, 0));
        txtProjectReq2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReq2.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectReq2.setBorder(null);
        txtProjectReq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReq2ActionPerformed(evt);
            }
        });

        lblProjectreq3.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectreq3.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectreq3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectreq3.setText("Requirement 3 :");

        txtProjectReq3.setEditable(false);
        txtProjectReq3.setBackground(new java.awt.Color(0, 0, 0));
        txtProjectReq3.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReq3.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectReq3.setBorder(null);
        txtProjectReq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReq3ActionPerformed(evt);
            }
        });

        lblProjectreq4.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectreq4.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectreq4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectreq4.setText("Requirement 4 :");

        txtProjectReq4.setEditable(false);
        txtProjectReq4.setBackground(new java.awt.Color(0, 0, 0));
        txtProjectReq4.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReq4.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectReq4.setBorder(null);
        txtProjectReq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReq4ActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 102, 0));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Submit");
        btnSave.setBorder(null);
        btnSave.setBorderPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 102, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back (1).png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblYear1.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblYear1.setForeground(new java.awt.Color(153, 153, 153));
        lblYear1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear1.setText("Region :");

        txtRegion.setEditable(false);
        txtRegion.setBackground(new java.awt.Color(0, 0, 0));
        txtRegion.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtRegion.setForeground(new java.awt.Color(255, 255, 255));
        txtRegion.setBorder(null);
        txtRegion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtLanguage.setEditable(false);
        txtLanguage.setBackground(new java.awt.Color(0, 0, 0));
        txtLanguage.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtLanguage.setForeground(new java.awt.Color(255, 255, 255));
        txtLanguage.setBorder(null);
        txtLanguage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblYear2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblYear2.setForeground(new java.awt.Color(153, 153, 153));
        lblYear2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear2.setText("Language : ");

        Req1ComboBox.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Req1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Status--", "Done", "Not Done" }));
        Req1ComboBox.setBorder(null);
        Req1ComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Req2ComboBox.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Req2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Status--", "Done", "Not Done" }));
        Req2ComboBox.setBorder(null);
        Req2ComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Req3ComboBox.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Req3ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Status--", "Done", "Not Done" }));
        Req3ComboBox.setBorder(null);
        Req3ComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Req3ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Req3ComboBoxActionPerformed(evt);
            }
        });

        Req4ComboBox.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Req4ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Status--", "Done", "Not Done" }));
        Req4ComboBox.setBorder(null);
        Req4ComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtSemester.setEditable(false);
        txtSemester.setBackground(new java.awt.Color(0, 0, 0));
        txtSemester.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtSemester.setForeground(new java.awt.Color(255, 255, 255));
        txtSemester.setBorder(null);
        txtSemester.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblLectures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lecture ID", "Lecture Name", "Lecture Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLectures);

        btnViewLecture.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        btnViewLecture.setText("View");
        btnViewLecture.setBorder(null);
        btnViewLecture.setBorderPainted(false);
        btnViewLecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLectureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectreq4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjectReq4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectreq3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjectReq3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectreq1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjectReq1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectreq2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjectReq2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Req1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Req2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Req3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Req4ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(505, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProjectDesc))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 161, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 440, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblProjectReferences)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtProjectReferences, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCourseID)
                                .addGap(31, 31, 31)
                                .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCourseName)
                                .addGap(18, 18, 18)
                                .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCourseDesc)
                                    .addComponent(lblYear)
                                    .addComponent(lblYear1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                                        .addComponent(lblYear2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSemester)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCourseDesc))))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewLecture, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseID)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseDesc)
                    .addComponent(txtCourseDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemester)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear1)
                            .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(btnViewLecture, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear2)
                            .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectReferences)
                    .addComponent(txtProjectReferences, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProjectName)
                    .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectDesc)
                    .addComponent(txtProjectDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectreq1)
                    .addComponent(txtProjectReq1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Req1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectreq2)
                    .addComponent(txtProjectReq2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Req2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectreq3)
                    .addComponent(txtProjectReq3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Req3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectreq4)
                    .addComponent(txtProjectReq4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Req4ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProjectReferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReferencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReferencesActionPerformed

    private void txtProjectDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectDescActionPerformed

    private void txtProjectReq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReq1ActionPerformed

    private void txtProjectReq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReq2ActionPerformed

    private void txtProjectReq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReq3ActionPerformed

    private void txtProjectReq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReq4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReq4ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String Requirement1 = Req1ComboBox.getSelectedItem().toString();
        String Requirement2 = Req2ComboBox.getSelectedItem().toString();
        String Requirement3 = Req3ComboBox.getSelectedItem().toString();
        String Requirement4 = Req4ComboBox.getSelectedItem().toString();
        String grade;
        Integer rank;

        int doneCount = 0;

        if (Requirement1.equalsIgnoreCase("Done")) {
            doneCount++;
        }

        if (Requirement2.equalsIgnoreCase("Done")) {
            doneCount++;
        }

        if (Requirement3.equalsIgnoreCase("Done")) {
            doneCount++;
        }

        if (Requirement4.equalsIgnoreCase("Done")) {
            doneCount++;
        }

        if (doneCount == 4) {
            grade = "A";
            rank = 1;
        } else if (doneCount == 3) {
            grade = "B";
            rank = 2;
        } else if (doneCount == 2) {
            grade = "C";
            rank = 3;
        } else if (doneCount == 1) {
            grade = "D";
             rank = 4;
        } else {
            grade = "Fail";
            rank = 5;
        }
        
                try {
            Connection connection = (Connection) DatabaseConnection.getConnection();

            // Define the SQL INSERT query
            String sql = "UPDATE coursesregistered SET require1 = ?, require2 = ?, require3 = ?, require4 = ?, grade = ? ,student_rank = ?, course_status =? WHERE courseid = ? AND nuid = ?";
           
            
            // Create a PreparedStatement
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
           

            // Bind the values to the placeholders
           
            preparedStatement.setString(1,  Requirement1);
            preparedStatement.setString(2, Requirement2);
            preparedStatement.setString(3, Requirement3);
            preparedStatement.setString(4, Requirement4);
            preparedStatement.setString(5, grade);
            preparedStatement.setInt(6, rank);
            preparedStatement.setString(7,"Completed" );
              preparedStatement.setInt(8, Integer.parseInt(selectedCourse));
              preparedStatement.setInt(9, Integer.parseInt(selectedNUID));
            // Bind values for lectures, projects, etc. in a similar manner

            // Execute the INSERT query
            preparedStatement.executeUpdate();

            preparedStatement.close();
//            DatabaseConnection.closeConnection(co);

            // Display a success message
            JOptionPane.showMessageDialog(mainframe, "Course Completed successfully.", "Save Successful", JOptionPane.INFORMATION_MESSAGE);
            CourseSubmitJPanel coursesubmit = new CourseSubmitJPanel(mainframe,selectedNUID,selectedCourse);
            mainframe.setRightComponent(coursesubmit);
           }catch (SQLException ex) {
            ex.printStackTrace();
            // Display an error message if there's an issue with saving the data
            JOptionPane.showMessageDialog(mainframe, "Error saving data.", "Save Failed", JOptionPane.ERROR_MESSAGE);
        }

        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
       myStudentCoursesJPanel mycourses= new myStudentCoursesJPanel(mainframe,selectedNUID);
        mainframe.setRightComponent(mycourses);
    }//GEN-LAST:event_btnBackActionPerformed

    private void Req3ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Req3ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Req3ComboBoxActionPerformed

    private void btnViewLectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLectureActionPerformed
          // TODO add your handling code here:
         int SelectedRowIndex = tblLectures.getSelectedRow();
         
         if(SelectedRowIndex<0)
         {
             JOptionPane.showMessageDialog(this, "Plesae select a row to delete");
             return;
         }
         
         DefaultTableModel model = (DefaultTableModel) tblLectures.getModel();
      
         
           Integer lectureid =Integer.parseInt(model.getValueAt(SelectedRowIndex, 0).toString());
           System.out.println(lectureid + " lectureid from viewstudent");
          
        ViewLectureJPanel viewlecture = new ViewLectureJPanel(mainframe,lectureid,selectedNUID,selectedCourse);
        mainframe.setRightComponent(viewlecture);
    }//GEN-LAST:event_btnViewLectureActionPerformed

    private void txtCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Req1ComboBox;
    private javax.swing.JComboBox<String> Req2ComboBox;
    private javax.swing.JComboBox<String> Req3ComboBox;
    private javax.swing.JComboBox<String> Req4ComboBox;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnViewLecture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseDesc;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblProjectDesc;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JLabel lblProjectReferences;
    private javax.swing.JLabel lblProjectreq1;
    private javax.swing.JLabel lblProjectreq2;
    private javax.swing.JLabel lblProjectreq3;
    private javax.swing.JLabel lblProjectreq4;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYear1;
    private javax.swing.JLabel lblYear2;
    private javax.swing.JTable tblLectures;
    private javax.swing.JTextField txtCourseDesc;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtProjectDesc;
    private javax.swing.JTextField txtProjectName;
    private javax.swing.JTextField txtProjectReferences;
    private javax.swing.JTextField txtProjectReq1;
    private javax.swing.JTextField txtProjectReq2;
    private javax.swing.JTextField txtProjectReq3;
    private javax.swing.JTextField txtProjectReq4;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
