/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminWorkArea;

import ui.MainJFrame;
import Database.DatabaseConnection;
import com.mysql.jdbc.Connection;
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.category.AbstractCategoryItemRenderer;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import ui.MainJFrame;
/**
 *
 * @author Abhinav Uni
 */
public class AdminMainJPanel extends javax.swing.JPanel {
    
    MainJFrame mainframe;

    /**
     * Creates new form AdminLandingJPanel
     */
    public AdminMainJPanel(MainJFrame mainframe) {
        initComponents();
                
        this.mainframe = mainframe;
        showPieChart();
    }
    
    public void showPieChart(){
            int agrade = 0;
            int bgrade = 0;
            int cgrade = 0;
            int dgrade = 0;
           DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                try {
             Connection connection = (Connection)DatabaseConnection.getConnection();
 
             // Define the SQL query to retrieve professor data
             String sql = "SELECT nuid FROM  coursesregistered WHERE grade='A'";
 
             PreparedStatement preparedStatement = connection.prepareStatement(sql);
             ResultSet resultSet = preparedStatement.executeQuery();
 
 
                        while (resultSet.next()) {
                            agrade++;
                        }
             String sql2 = "SELECT nuid FROM coursesregistered WHERE grade='B'";
 
             PreparedStatement preparedStatement2 = connection.prepareStatement(sql2);
             ResultSet resultSet2 = preparedStatement2.executeQuery();
 
 
                        while (resultSet2.next()) {
                            bgrade++;
                        }
                        System.out.println(bgrade);
                String sql3 = "SELECT nuid FROM coursesregistered WHERE grade='C'";
 
             PreparedStatement preparedStatement3 = connection.prepareStatement(sql3);
             ResultSet resultSet3 = preparedStatement3.executeQuery();
 
 
                        while (resultSet3.next()) {
                            cgrade++;
                        }
                         System.out.println(cgrade);
                         String sql4 = "SELECT nuid FROM coursesregistered WHERE  grade='D'";
 
             PreparedStatement preparedStatement4 = connection.prepareStatement(sql4);
             ResultSet resultSet4 = preparedStatement4.executeQuery();
 
 
                        while (resultSet4.next()) {
                            dgrade++;
                        }
                          System.out.println(dgrade);
 
                   resultSet.close();
                   preparedStatement.close();
               } catch (Exception e) {
                   e.printStackTrace();
               } finally {
           //        DatabaseConnection.closeConnection();
                 }
                dataset.setValue(agrade, "A", "Student Performance");
                dataset.setValue(bgrade, "B", "Student Performance");
                dataset.setValue(cgrade, "C", "Student Performance");
                dataset.setValue(dgrade, "D", "Student Performance");
 
                JFreeChart chart = ChartFactory.createBarChart("Bar Chart", "Grades", "Count", dataset);
                ChartPanel panel = new ChartPanel(chart);
 
                JFrame frame = new JFrame("Bar Chart");
                frame.getContentPane().add(panel);
                frame.pack();
                frame.setVisible(true);

 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("WELCOME ADMIN!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(260, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
