/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GovernmentWorkArea;

import LandingUI.MainJFrame;
import LandingUI.MenuPH;

/**
 *
 * @author Abhinav Uni
 */
public class ManageResourceJPanel extends javax.swing.JPanel {
    
    private MainJFrame mainframe;
    private int selectedNUID;

    /**
     * Creates new form ManageResourceJPanel
     */
    public ManageResourceJPanel(MainJFrame mainframe,int selectedNUID) {
        initComponents();
        
        this.mainframe = mainframe;
        this.selectedNUID = selectedNUID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        logininfo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblorganisation1 = new javax.swing.JLabel();
        lblenterprise1 = new javax.swing.JLabel();
        txtenterprise1 = new javax.swing.JTextField();
        txtorganisation1 = new javax.swing.JTextField();
        lbldepartment1 = new javax.swing.JLabel();
        txtdepartment1 = new javax.swing.JTextField();
        lbldivision1 = new javax.swing.JLabel();
        txtdivision1 = new javax.swing.JTextField();
        lbltaxamount = new javax.swing.JLabel();
        txttaxamount1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 0, 102));

        backbtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        backbtn.setText("Home");
        backbtn.setBorder(null);
        backbtn.setBorderPainted(false);
        backbtn.setContentAreaFilled(false);
        backbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/US logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("United States Government");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 3, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("Department of Internal Affairs, Washington DC");

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Education, Safety and basic utilities to the citizens of the United States. Everybody is expected to abide by the constitution regardless of the position.");

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Please report any critical incidents that may be  challenging the peace and justice of the country. These incidents include, and are not limited to, problems in providing Healthcare,");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Governing Body", "Budget Allocated", "Complaints raised"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 3, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View the state money allocation within government :");

        jButton3.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setText("Manage Budget");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton4.setBackground(new java.awt.Color(204, 0, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View Complaints");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        logininfo.setBackground(new java.awt.Color(102, 0, 102));
        logininfo.setFont(new java.awt.Font("Segoe UI Variable", 1, 21)); // NOI18N
        logininfo.setForeground(new java.awt.Color(255, 255, 255));
        logininfo.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("logged in as :");

        lblorganisation1.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        lblorganisation1.setForeground(new java.awt.Color(153, 153, 153));
        lblorganisation1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblorganisation1.setText("Organisation:");

        lblenterprise1.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        lblenterprise1.setForeground(new java.awt.Color(153, 153, 153));
        lblenterprise1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblenterprise1.setText("Enterprise:");

        txtenterprise1.setBackground(new java.awt.Color(102, 0, 102));
        txtenterprise1.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        txtenterprise1.setForeground(new java.awt.Color(255, 255, 255));
        txtenterprise1.setBorder(null);

        txtorganisation1.setBackground(new java.awt.Color(102, 0, 102));
        txtorganisation1.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        txtorganisation1.setForeground(new java.awt.Color(255, 255, 255));
        txtorganisation1.setBorder(null);

        lbldepartment1.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        lbldepartment1.setForeground(new java.awt.Color(153, 153, 153));
        lbldepartment1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldepartment1.setText("Department:");

        txtdepartment1.setBackground(new java.awt.Color(102, 0, 102));
        txtdepartment1.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        txtdepartment1.setForeground(new java.awt.Color(255, 255, 255));
        txtdepartment1.setBorder(null);

        lbldivision1.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        lbldivision1.setForeground(new java.awt.Color(153, 153, 153));
        lbldivision1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldivision1.setText("Division:");

        txtdivision1.setBackground(new java.awt.Color(102, 0, 102));
        txtdivision1.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        txtdivision1.setForeground(new java.awt.Color(255, 255, 255));
        txtdivision1.setBorder(null);

        lbltaxamount.setBackground(new java.awt.Color(153, 153, 153));
        lbltaxamount.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lbltaxamount.setForeground(new java.awt.Color(255, 255, 255));
        lbltaxamount.setText("Total Tax Money Accumulated");
        lbltaxamount.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txttaxamount1.setBackground(new java.awt.Color(102, 0, 102));
        txttaxamount1.setFont(new java.awt.Font("Segoe UI Black", 1, 21)); // NOI18N
        txttaxamount1.setForeground(new java.awt.Color(255, 255, 255));
        txttaxamount1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txttaxamount1.setBorder(null);
        txttaxamount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttaxamount1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbltaxamount)
                                    .addGap(13, 13, 13)
                                    .addComponent(txttaxamount1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblenterprise1)
                            .addGap(5, 5, 5)
                            .addComponent(txtenterprise1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(lblorganisation1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(txtorganisation1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(lbldepartment1)
                            .addGap(5, 5, 5)
                            .addComponent(txtdepartment1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(lbldivision1)
                            .addGap(5, 5, 5)
                            .addComponent(txtdivision1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backbtn)
                            .addGap(377, 377, 377)
                            .addComponent(jLabel13)
                            .addGap(13, 13, 13)
                            .addComponent(logininfo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(logininfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblenterprise1)
                    .addComponent(txtenterprise1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblorganisation1)
                    .addComponent(txtorganisation1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldepartment1)
                    .addComponent(txtdepartment1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldivision1)
                    .addComponent(txtdivision1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttaxamount1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbltaxamount))
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        
        GovernmentLandingJPanel govtland = new GovernmentLandingJPanel(mainframe,selectedNUID);
        mainframe.setRightComponent(govtland);
        MenuPH placeholder = new MenuPH(mainframe);
        mainframe.setLeftComponent(placeholder);
    }//GEN-LAST:event_backbtnActionPerformed

    private void txttaxamount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttaxamount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttaxamount1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbldepartment1;
    private javax.swing.JLabel lbldivision1;
    private javax.swing.JLabel lblenterprise1;
    private javax.swing.JLabel lblorganisation1;
    private javax.swing.JLabel lbltaxamount;
    private javax.swing.JTextField logininfo;
    private javax.swing.JTextField txtdepartment1;
    private javax.swing.JTextField txtdivision1;
    private javax.swing.JTextField txtenterprise1;
    private javax.swing.JTextField txtorganisation1;
    private javax.swing.JTextField txttaxamount1;
    // End of variables declaration//GEN-END:variables
}
