/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import homework_1.Address;
import homework_1.Doctor;
import homework_1.Driver;
import homework_1.Insurancecoverage;
import homework_1.Patient;
import homework_1.Person;
import homework_1.Vehicleregistration;

/**
 *
 * @author Vaishnavi Choukwale
 */
public class MainJFrame extends javax.swing.JFrame {
    
    Person person;
    Address address;
    Driver driver;
    Patient patient;
    Doctor doctor;
    Vehicleregistration vehicleregistration;
    Insurancecoverage insurancecoverage;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        person = new Person();
        address = new Address();
        driver = new Driver();
        patient = new Patient();
        doctor = new Doctor();
        vehicleregistration = new Vehicleregistration();
        insurancecoverage = new Insurancecoverage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        viewPanel = new javax.swing.JPanel();
        createPanel = new javax.swing.JPanel();
        btnCreatePerson = new javax.swing.JButton();
        btnCreateAddress = new javax.swing.JButton();
        btnCreateDriverLicense = new javax.swing.JButton();
        btnCreateVehicleRegistration = new javax.swing.JButton();
        btnCreatePatient = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();
        btnCreateInsuranceCoverage = new javax.swing.JButton();
        btnViewPatientReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 37, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 37));
        setSize(new java.awt.Dimension(0, 0));

        viewPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(viewPanel);

        createPanel.setBackground(new java.awt.Color(0, 0, 0));

        btnCreatePerson.setText("Personal Details");
        btnCreatePerson.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnCreateAddress.setText("Address");
        btnCreateAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddressActionPerformed(evt);
            }
        });

        btnCreateDriverLicense.setText("Driver License");
        btnCreateDriverLicense.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreateDriverLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDriverLicenseActionPerformed(evt);
            }
        });

        btnCreateVehicleRegistration.setText("Vehicle Registration");
        btnCreateVehicleRegistration.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreateVehicleRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVehicleRegistrationActionPerformed(evt);
            }
        });

        btnCreatePatient.setText("Patient Details");
        btnCreatePatient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        btnCreateDoctor.setText("Doctor Details");
        btnCreateDoctor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });

        btnCreateInsuranceCoverage.setText("Insurance Coverage");
        btnCreateInsuranceCoverage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreateInsuranceCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateInsuranceCoverageActionPerformed(evt);
            }
        });

        btnViewPatientReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewPatientReport.setText("Patient Report");
        btnViewPatientReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViewPatientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateDriverLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreatePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateVehicleRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreatePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateInsuranceCoverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPatientReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnCreatePerson)
                .addGap(18, 18, 18)
                .addComponent(btnCreateAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateDriverLicense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateVehicleRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreatePatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateDoctor)
                .addGap(18, 18, 18)
                .addComponent(btnCreateInsuranceCoverage)
                .addGap(18, 18, 18)
                .addComponent(btnViewPatientReport)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(createPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(splitPane)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddressActionPerformed
        // TODO add your handling code here:
        CreateAddressJPanel addressPanel = new CreateAddressJPanel(address);
        splitPane.setRightComponent(addressPanel);
    }//GEN-LAST:event_btnCreateAddressActionPerformed

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel personPanel = new CreatePersonJPanel(person);
        splitPane.setRightComponent(personPanel);
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnCreateDriverLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDriverLicenseActionPerformed
        // TODO add your handling code here:
        CreateDriverJPanel driverPanel = new CreateDriverJPanel(driver);
        splitPane.setRightComponent(driverPanel);
    }//GEN-LAST:event_btnCreateDriverLicenseActionPerformed

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        // TODO add your handling code here:
        CreateDoctorJPanel doctorPanel = new CreateDoctorJPanel(doctor);
        splitPane.setRightComponent(doctorPanel);
    }//GEN-LAST:event_btnCreateDoctorActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        CreatePatientJPanel patientPanel = new CreatePatientJPanel(patient);
        splitPane.setRightComponent(patientPanel);
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnCreateVehicleRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVehicleRegistrationActionPerformed
        // TODO add your handling code here:
        CreateVehicleregistrationJPanel vehicleregistrationPanel = new CreateVehicleregistrationJPanel(vehicleregistration);
        splitPane.setRightComponent(vehicleregistrationPanel);
    }//GEN-LAST:event_btnCreateVehicleRegistrationActionPerformed

    private void btnCreateInsuranceCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInsuranceCoverageActionPerformed
        // TODO add your handling code here:
        CreateInsurancecoverageJPanel insurancecoveragePanel = new CreateInsurancecoverageJPanel(insurancecoverage);
        splitPane.setRightComponent(insurancecoveragePanel);
    }//GEN-LAST:event_btnCreateInsuranceCoverageActionPerformed

    private void btnViewPatientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientReportActionPerformed
        // TODO add your handling code here:
        DisplayReport tempp = new DisplayReport(person,address,doctor,driver,patient,vehicleregistration,insurancecoverage);
        splitPane.setRightComponent(tempp);
    }//GEN-LAST:event_btnViewPatientReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAddress;
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnCreateDriverLicense;
    private javax.swing.JButton btnCreateInsuranceCoverage;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnCreateVehicleRegistration;
    private javax.swing.JButton btnViewPatientReport;
    private javax.swing.JPanel createPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
