/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProfessorWorkArea;

import ui.MainJFrame;
import ProfessorWorkArea.ProfProfileJPanel;
import javax.swing.JOptionPane;
import Database.DatabaseConnection;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;



import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;

/**
 *
 * @author Abhinav Uni
 */
public class UpdateMyCourseJPanel extends javax.swing.JPanel {
    
    
    private String selectedNUID;
    private String selectedCourse;
    
    MainJFrame mainframe;

    /**
     * Creates new form CreateCourseJPanel
     */
    public UpdateMyCourseJPanel(MainJFrame mainframe,String selectedNUID, String selectedCourse) {
        this.selectedNUID = selectedNUID;
        initComponents();
        
        this.selectedCourse = selectedCourse;
        this.mainframe = mainframe;
        
        viewCourseDetails();
    }

    private void viewCourseDetails() {
//    String NUID = txtNUID.getText();
    
    try {
         Connection connection = (Connection)DatabaseConnection.getConnection();
//        selectedNUID = "1234567890";
        // Define the SQL query to retrieve user details based on NUID
        String sql = "SELECT courseid, nuid, coursename, course_desc, semester, year,region,language, projectname, reference_link, project_desc, require1, require2, require3, require4 FROM courses WHERE courseid = ?";
    
            // Create a PreparedStatement
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            // Bind the selectedNUID value to the placeholder
            preparedStatement.setString(1, selectedCourse);
           

        ResultSet resultSet = preparedStatement.executeQuery();
//         System.out.println(resultSet.getString("Name") + "hello");
        if (resultSet.next()) {
            // Populate the text fields with retrieved data
        String CourseID = resultSet.getString("courseid");
        String retrievedCourseName = resultSet.getString("coursename");
        String retrievedCourseDesc = resultSet.getString("course_desc");
        String retrievedSemester = resultSet.getString("semester");
        System.out.println(retrievedSemester + "retrievedSemester");
        int retrievedYear = resultSet.getInt("year");
        String retrievedRegion = resultSet.getString("region");
         String retrievedLanguage = resultSet.getString("language");
        String retrievedProjectName = resultSet.getString("projectname");
        String retrievedReferenceLink = resultSet.getString("reference_link");
        String retrievedProjectDesc = resultSet.getString("project_desc");
        String retrievedRequire1 = resultSet.getString("require1");
        String retrievedRequire2 = resultSet.getString("require2");
        String retrievedRequire3 = resultSet.getString("require3");
        String retrievedRequire4 = resultSet.getString("require4");

        // Now, populate your UI fields with the retrieved data
        txtCourseID.setText(String.valueOf(CourseID));
  
        txtCourseName.setText(retrievedCourseName);
        txtCourseDesc.setText(retrievedCourseDesc);
        SemesterComboBox.setSelectedItem(retrievedSemester);
        YearComboBox.setSelectedItem(String.valueOf(retrievedYear));
        RegionComboBox.setSelectedItem(String.valueOf(retrievedRegion));
        LanguageComboBox.setSelectedItem(String.valueOf(retrievedLanguage));
        txtProjectName.setText(retrievedProjectName);
        txtProjectDesc.setText(retrievedProjectDesc);
        txtProjectReferences.setText(retrievedReferenceLink);
        txtProjectReq1.setText(retrievedRequire1);
        txtProjectReq2.setText(retrievedRequire2);
        txtProjectReq3.setText(retrievedRequire3);
        txtProjectReq4.setText(retrievedRequire4);
        

            
            
            // ... set the other fields similarly
        } else {
            System.out.println("User not found.");
        }

        resultSet.close();
        preparedStatement.close();
       
    } catch (SQLException e) {
        e.printStackTrace();
    }finally {
//        DatabaseConnection.closeConnection();
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private String professorname(){
        String professorName = null;
        try {
        Connection connection = (Connection)DatabaseConnection.getConnection();
        int professorNUID = Integer.parseInt(selectedNUID); // Parse selectedNUID to an integer

        String sql = "SELECT name FROM users WHERE nuid = ? AND profile_type = 'Professor'";
        PreparedStatement preparedStatement = connection.prepareStatement(sql);
        preparedStatement.setInt(1, professorNUID);
        System.out.println(professorNUID + "professorNUID");

        ResultSet resultSet = preparedStatement.executeQuery();

        if (resultSet.next()) {
            professorName = resultSet.getString("name");
            System.out.println("Professor Name: " + professorName);

            // You can use the studentName as needed, for example, displaying it in your UI.
        } else {
            System.out.println("No professor with the provided NUID and profile type 'Student' found.");
            // Handle the case where no matching student is found.
        }

        resultSet.close();
        preparedStatement.close();
    } catch (SQLException e) {
        e.printStackTrace();
        // Handle any SQL exceptions that may occur.
    }

    return  professorName; 
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        lblCourseDesc = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        txtCourseDesc = new javax.swing.JTextField();
        lblCourseName = new javax.swing.JLabel();
        lblCourseID = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        lblProjectName = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblProjectReferences = new javax.swing.JLabel();
        txtProjectReferences = new javax.swing.JTextField();
        txtProjectDesc = new javax.swing.JTextField();
        lblProjectDesc = new javax.swing.JLabel();
        lblProjectreq1 = new javax.swing.JLabel();
        txtProjectReq1 = new javax.swing.JTextField();
        lblProjectreq2 = new javax.swing.JLabel();
        txtProjectReq2 = new javax.swing.JTextField();
        lblProjectreq3 = new javax.swing.JLabel();
        txtProjectReq3 = new javax.swing.JTextField();
        lblProjectreq4 = new javax.swing.JLabel();
        txtProjectReq4 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        SemesterComboBox = new javax.swing.JComboBox<>();
        lblYear1 = new javax.swing.JLabel();
        lblYear2 = new javax.swing.JLabel();
        YearComboBox = new javax.swing.JComboBox<>();
        RegionComboBox = new javax.swing.JComboBox<>();
        LanguageComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 102));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create New Course");

        txtCourseName.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N

        lblCourseDesc.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblCourseDesc.setForeground(new java.awt.Color(153, 153, 153));
        lblCourseDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCourseDesc.setText("Course Desc :");

        lblYear.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblYear.setForeground(new java.awt.Color(153, 153, 153));
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear.setText("Year : ");

        lblSemester.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblSemester.setForeground(new java.awt.Color(153, 153, 153));
        lblSemester.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSemester.setText("Semester : ");

        txtCourseDesc.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N

        lblCourseName.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblCourseName.setForeground(new java.awt.Color(153, 153, 153));
        lblCourseName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCourseName.setText("Course Name : ");

        lblCourseID.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblCourseID.setForeground(new java.awt.Color(153, 153, 153));
        lblCourseID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCourseID.setText("Course ID : ");

        txtCourseID.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N

        lblProjectName.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectName.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectName.setText("Project Name: ");

        txtProjectName.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add Final Project");

        lblProjectReferences.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectReferences.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectReferences.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectReferences.setText("References Link :");

        txtProjectReferences.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReferencesActionPerformed(evt);
            }
        });

        txtProjectDesc.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectDescActionPerformed(evt);
            }
        });

        lblProjectDesc.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectDesc.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectDesc.setText(" Project Desc :");

        lblProjectreq1.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectreq1.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectreq1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectreq1.setText("Requirement 1:");

        txtProjectReq1.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReq1ActionPerformed(evt);
            }
        });

        lblProjectreq2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectreq2.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectreq2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectreq2.setText("Requirement 2 :");

        txtProjectReq2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReq2ActionPerformed(evt);
            }
        });

        lblProjectreq3.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectreq3.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectreq3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectreq3.setText("Requirement 3 :");

        txtProjectReq3.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReq3ActionPerformed(evt);
            }
        });

        lblProjectreq4.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblProjectreq4.setForeground(new java.awt.Color(153, 153, 153));
        lblProjectreq4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProjectreq4.setText("Requirement 4 :");

        txtProjectReq4.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        txtProjectReq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectReq4ActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 255, 255));
        btnSave.setForeground(new java.awt.Color(0, 102, 102));
        btnSave.setText("Update Lectures");
        btnSave.setBorder(null);
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 102, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back (1).png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        SemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Fall", "Spring" }));
        SemesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemesterComboBoxActionPerformed(evt);
            }
        });

        lblYear1.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblYear1.setForeground(new java.awt.Color(153, 153, 153));
        lblYear1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear1.setText("Region :");

        lblYear2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblYear2.setForeground(new java.awt.Color(153, 153, 153));
        lblYear2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear2.setText("Language : ");

        YearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "2022", "2023", "2024" }));
        YearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearComboBoxActionPerformed(evt);
            }
        });

        RegionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Boston", "New York", "Seattle" }));

        LanguageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "English", "Chinese", "Spanish" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectreq4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjectReq4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectreq3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjectReq3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectreq2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjectReq2)))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCourseID)
                                .addGap(31, 31, 31)
                                .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                                .addComponent(lblCourseName)
                                .addGap(18, 18, 18)
                                .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCourseDesc)
                                    .addComponent(lblYear)
                                    .addComponent(lblYear1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RegionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblYear2)
                                        .addGap(18, 18, 18)
                                        .addComponent(LanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCourseDesc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSemester)
                                        .addGap(18, 18, 18)
                                        .addComponent(SemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblProjectreq1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProjectReq1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblProjectReferences)
                                .addGap(18, 18, 18)
                                .addComponent(txtProjectReferences, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProjectDesc)
                                .addGap(18, 18, 18)
                                .addComponent(txtProjectDesc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblProjectName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseID)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseDesc)
                    .addComponent(txtCourseDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(lblSemester)
                    .addComponent(SemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYear2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblYear1)
                        .addComponent(RegionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectReferences)
                    .addComponent(txtProjectReferences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProjectName)
                    .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectDesc)
                    .addComponent(txtProjectDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectreq1)
                    .addComponent(txtProjectReq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectreq2)
                    .addComponent(txtProjectReq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectreq3)
                    .addComponent(txtProjectReq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectreq4)
                    .addComponent(txtProjectReq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProjectReferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReferencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReferencesActionPerformed

    private void txtProjectDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectDescActionPerformed

    private void txtProjectReq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReq1ActionPerformed

    private void txtProjectReq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReq2ActionPerformed

    private void txtProjectReq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReq3ActionPerformed

    private void txtProjectReq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectReq4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectReq4ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String selectedSemester = SemesterComboBox.getSelectedItem().toString();
        String selectedYear = YearComboBox.getSelectedItem().toString();
        String selectedRegion = RegionComboBox.getSelectedItem().toString();
        String selectedLanguage = LanguageComboBox.getSelectedItem().toString();
        int CourseID = Integer.parseInt(txtCourseID.getText());
        Integer NUID = Integer.parseInt(selectedNUID);
        
        String courseName = txtCourseName.getText();
        String courseDescription = txtCourseDesc.getText();
        String semester = selectedSemester;
        int year = Integer.parseInt(selectedYear); 
        String  ProjectName = txtProjectName.getText();
        String ProjectDescription = txtProjectDesc.getText();
        String ProjectReferences = txtProjectReferences.getText();
        String ProjectRequirement1 = txtProjectReq1.getText();
        String ProjectRequirement2 = txtProjectReq2.getText();
        String ProjectRequirement3 = txtProjectReq3.getText();
        String ProjectRequirement4 = txtProjectReq4.getText();
        
                try {
            Connection connection = (Connection) DatabaseConnection.getConnection();

            // Define the SQL INSERT query
            String sql = "UPDATE courses SET courseid = ?, coursename = ?, course_desc = ?, semester = ?, year = ?, region = ?, language = ?,projectname = ?, reference_link = ?, project_desc = ?, require1 = ?, require2 = ?, require3 = ?, require4 = ? WHERE courseid = ?";

            
            // Create a PreparedStatement
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            // Bind the values to the placeholders
            preparedStatement.setInt(1, CourseID);
 
            preparedStatement.setString(2, courseName);
            preparedStatement.setString(3, courseDescription);
            preparedStatement.setString(4, semester);
            preparedStatement.setInt(5, year);
            preparedStatement.setString(6,  selectedRegion);
             preparedStatement.setString(7, selectedLanguage);
           
            preparedStatement.setString(8, ProjectName);
            preparedStatement.setString(9, ProjectDescription);
            preparedStatement.setString(10, ProjectReferences);
            preparedStatement.setString(11, ProjectRequirement1);
            preparedStatement.setString(12, ProjectRequirement2);
            preparedStatement.setString(13, ProjectRequirement3);
            preparedStatement.setString(14, ProjectRequirement4);
            preparedStatement.setInt(15, CourseID);
           
            // Bind values for lectures, projects, etc. in a similar manner

            // Execute the INSERT query
            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                // Update was successful
                JOptionPane.showMessageDialog(mainframe, "Data saved successfully.", "Save Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                
                 JOptionPane.showMessageDialog(mainframe, "Update failed.", "Update Failed", JOptionPane.ERROR_MESSAGE);
                // Handle the case where no rows were updated (e.g., the course with the given CourseID does not exist)
            }
            
            UpdateLectureJPanel lecture = new UpdateLectureJPanel(mainframe,selectedCourse,selectedNUID);
            mainframe.setRightComponent(lecture);

            preparedStatement.close();
//            DatabaseConnection.closeConnection(co);

            // Display a success message
            
           }catch (SQLException ex) {
            ex.printStackTrace();
            // Display an error message if there's an issue with saving the data
            JOptionPane.showMessageDialog(mainframe, "Error saving data.", "Save Failed", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        ProfProfileJPanel proflanding = new ProfProfileJPanel(mainframe,selectedNUID);
        mainframe.setRightComponent(proflanding);
    }//GEN-LAST:event_btnBackActionPerformed

    private void YearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearComboBoxActionPerformed

    private void SemesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemesterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemesterComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LanguageComboBox;
    private javax.swing.JComboBox<String> RegionComboBox;
    private javax.swing.JComboBox<String> SemesterComboBox;
    private javax.swing.JComboBox<String> YearComboBox;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseDesc;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblProjectDesc;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JLabel lblProjectReferences;
    private javax.swing.JLabel lblProjectreq1;
    private javax.swing.JLabel lblProjectreq2;
    private javax.swing.JLabel lblProjectreq3;
    private javax.swing.JLabel lblProjectreq4;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYear1;
    private javax.swing.JLabel lblYear2;
    private javax.swing.JTextField txtCourseDesc;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtProjectDesc;
    private javax.swing.JTextField txtProjectName;
    private javax.swing.JTextField txtProjectReferences;
    private javax.swing.JTextField txtProjectReq1;
    private javax.swing.JTextField txtProjectReq2;
    private javax.swing.JTextField txtProjectReq3;
    private javax.swing.JTextField txtProjectReq4;
    // End of variables declaration//GEN-END:variables
}
