/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

import CitizenWorkArea.CitizenLandingJPanel;
import Database.DatabaseConnection;
import GovernmentWorkArea.GovernmentLandingJPanel;
import LandingUI.CitizenLanding;
import LandingUI.GovernmentLanding;
import LandingUI.MainJFrame;
import Register.RequestAccess;
import UserProfiles.createuserprofile;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhinav Uni
 */
public class CitizenLogin extends javax.swing.JPanel {
    
    private MainJFrame mainframe;
    private int selectedNUID;
    /**
     * Creates new form GovernmentLogin
     */
    public CitizenLogin(MainJFrame mainframe) {
        initComponents();
        
        this.mainframe = mainframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtCitizenLoginPassword = new javax.swing.JTextField();
        govtloginbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        applyssnbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 102));
        setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot__126_-removebg-preview.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("SSN :");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password :");

        txtSSN.setBackground(new java.awt.Color(102, 102, 102));
        txtSSN.setFont(new java.awt.Font("Segoe UI Variable", 1, 21)); // NOI18N
        txtSSN.setForeground(new java.awt.Color(255, 255, 255));
        txtSSN.setBorder(null);
        txtSSN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtSSNMouseMoved(evt);
            }
        });
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        txtCitizenLoginPassword.setBackground(new java.awt.Color(102, 102, 102));
        txtCitizenLoginPassword.setFont(new java.awt.Font("Segoe UI Variable", 1, 21)); // NOI18N
        txtCitizenLoginPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtCitizenLoginPassword.setBorder(null);
        txtCitizenLoginPassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtCitizenLoginPasswordMouseMoved(evt);
            }
        });
        txtCitizenLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitizenLoginPasswordActionPerformed(evt);
            }
        });

        govtloginbtn.setBackground(new java.awt.Color(0, 153, 0));
        govtloginbtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        govtloginbtn.setForeground(new java.awt.Color(255, 255, 255));
        govtloginbtn.setText("Login");
        govtloginbtn.setBorder(null);
        govtloginbtn.setBorderPainted(false);
        govtloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                govtloginbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("New here?");

        applyssnbtn.setBackground(new java.awt.Color(255, 204, 0));
        applyssnbtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        applyssnbtn.setText("Apply for SSN");
        applyssnbtn.setBorder(null);
        applyssnbtn.setBorderPainted(false);
        applyssnbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        applyssnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyssnbtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 2)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 2)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(applyssnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(govtloginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCitizenLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(applyssnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSSN)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtCitizenLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addComponent(govtloginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        CitizenLanding citland = new CitizenLanding(mainframe);
        mainframe.setRightComponent(citland);
        GovernmentLanding govtland = new GovernmentLanding(mainframe);
        mainframe.setLeftComponent(govtland);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCitizenLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitizenLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCitizenLoginPasswordActionPerformed

    private void applyssnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyssnbtnActionPerformed
        // TODO add your handling code here:
        
        RequestAccess reqacc = new RequestAccess(mainframe);
        mainframe.setRightComponent(reqacc);
    }//GEN-LAST:event_applyssnbtnActionPerformed

    private void govtloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_govtloginbtnActionPerformed
        // TODO add your handling code here:
        
//        // SSN Validation
//        String ssn = txtSSN.getText();
//        if (!ssn.matches("\\d{5}")) {
//            JOptionPane.showMessageDialog(this, "Please Enter Valid 5 Digit SSN.");
//        return; // Stop execution if validation fails
//        }
//        
//        // Password Validation
//        String password = txtCitizenLoginPassword.getText(); 
//        if (!password.matches("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,20}$")) {
//            JOptionPane.showMessageDialog(this, "Please Enter a Strong Password with a length between 8 and 20 characters.");
//        return; // Stop execution if validation fails
//        }
        
        try{
            
            Connection connection = (Connection)DatabaseConnection.getConnection();
            String userid = txtSSN.getText();
            if (!userid.matches("\\d{5}")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid 5 Digit SSN.");
            return; // Stop execution if validation fails
            }
            
            String password = txtCitizenLoginPassword.getText();
            if (!password.matches("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,20}$")) {
            JOptionPane.showMessageDialog(this, "Please Enter a Strong Password with a length between 8 and 20 characters.");
            return; // Stop execution if validation fails
            }
            
            
            String sql = "SELECT userid, hashedpassword FROM users WHERE userid = ?";

            
            PreparedStatement preparedStatement = (PreparedStatement) connection.prepareStatement(sql);
            preparedStatement.setInt(1, Integer.parseInt(userid));

            ResultSet rs = preparedStatement.executeQuery();
            if (rs.next()) {
                String NUID = rs.getString("userid");
                selectedNUID = Integer.parseInt(NUID);
                String hashedPasswordFromDB = rs.getString("hashedpassword");

                createuserprofile userProfile = new createuserprofile();

                if (userProfile.checkPassword(password, hashedPasswordFromDB)) {
                    System.out.println("selectedNUID: " + selectedNUID);
                    
                     JOptionPane.showMessageDialog(this, "User Logged in Successfully");
                     CitizenLandingJPanel govtland = new   CitizenLandingJPanel(mainframe,selectedNUID);
                     mainframe.setRightComponent(govtland);
                } else {
                    System.out.println("Login failed");
                    JOptionPane.showMessageDialog(this, "Username or password is incorrect");
                    txtSSN.setText("");
                    txtCitizenLoginPassword.setText("");
                }
            } else {
                System.out.println("User not found");
                JOptionPane.showMessageDialog(this, "Username or password is incorrect");
                txtSSN.setText("");
                txtCitizenLoginPassword.setText("");
            }

               // Execute the professor INSERT query
            
             
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
          
    }//GEN-LAST:event_govtloginbtnActionPerformed

    private void txtSSNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSSNMouseMoved
        // TODO add your handling code here:
        txtSSN.setToolTipText("Enter Valid 5 Digit SSN");
    }//GEN-LAST:event_txtSSNMouseMoved

    private void txtCitizenLoginPasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCitizenLoginPasswordMouseMoved
        // TODO add your handling code here:
        txtCitizenLoginPassword.setToolTipText("Enter Strong Password");
    }//GEN-LAST:event_txtCitizenLoginPasswordMouseMoved

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyssnbtn;
    private javax.swing.JButton govtloginbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCitizenLoginPassword;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
}
