/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

import Database.DatabaseConnection;
import GovernmentWorkArea.GovernmentLandingJPanel;
import LandingUI.CitizenLanding;
import LandingUI.GovernmentLanding;
import LandingUI.MainJFrame;
import Register.RequestAccess;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import UserProfiles.createuserprofile;

/**
 *
 * @author Abhinav Uni
 */
public class GovernmentLogin extends javax.swing.JPanel {
    
    private MainJFrame mainframe;

    /**
     * Creates new form GovernmentLogin
     */
    public GovernmentLogin(MainJFrame mainframe) {
        initComponents();
        
        this.mainframe = mainframe;
        Comboenterprise.setVisible(false);
        Comboorg.setVisible(false);
        Combodpt.setVisible(false);
        Combodivision.setVisible(false);
        lblenterprise.setVisible(false);
        lblorg.setVisible(false);
        lbldpt.setVisible(false);
        lbldivision.setVisible(false);
        Combodomain.setVisible(false);
        lblCombodomain.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        govtloginbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        reqaccessbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbldivision = new javax.swing.JLabel();
        Combodivision = new javax.swing.JComboBox<>();
        lblCombodomain = new javax.swing.JLabel();
        Combodomain = new javax.swing.JComboBox<>();
        lblenterprise = new javax.swing.JLabel();
        Comboenterprise = new javax.swing.JComboBox<>();
        lbldpt = new javax.swing.JLabel();
        Combodpt = new javax.swing.JComboBox<>();
        lblorg = new javax.swing.JLabel();
        Comboorg = new javax.swing.JComboBox<>();
        lblrole = new javax.swing.JLabel();
        Comborole = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        backbtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        backbtn.setText("Back");
        backbtn.setBorder(null);
        backbtn.setBorderPainted(false);
        backbtn.setContentAreaFilled(false);
        backbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/US logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choose login");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Government ID :");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Passcode :");

        txtusername.setBackground(new java.awt.Color(102, 102, 102));
        txtusername.setFont(new java.awt.Font("Segoe UI Variable", 1, 21)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setBorder(null);
        txtusername.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtusernameMouseMoved(evt);
            }
        });

        txtpassword.setBackground(new java.awt.Color(102, 102, 102));
        txtpassword.setFont(new java.awt.Font("Segoe UI Variable", 1, 21)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(null);
        txtpassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtpasswordMouseMoved(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        govtloginbtn.setBackground(new java.awt.Color(0, 153, 0));
        govtloginbtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        govtloginbtn.setForeground(new java.awt.Color(255, 255, 255));
        govtloginbtn.setText("Login");
        govtloginbtn.setBorder(null);
        govtloginbtn.setBorderPainted(false);
        govtloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                govtloginbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("New here?");

        reqaccessbtn.setBackground(new java.awt.Color(255, 204, 0));
        reqaccessbtn.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        reqaccessbtn.setText("Register");
        reqaccessbtn.setBorder(null);
        reqaccessbtn.setBorderPainted(false);
        reqaccessbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reqaccessbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqaccessbtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 2)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");

        lbldivision.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lbldivision.setForeground(new java.awt.Color(153, 153, 153));
        lbldivision.setText("Division:");

        Combodivision.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Combodivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        Combodivision.setBorder(null);
        Combodivision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Combodivision.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CombodivisionMouseMoved(evt);
            }
        });

        lblCombodomain.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblCombodomain.setForeground(new java.awt.Color(153, 153, 153));
        lblCombodomain.setText("Domain:");

        Combodomain.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Combodomain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "enterprise", "organisation", "department", "division" }));
        Combodomain.setBorder(null);
        Combodomain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Combodomain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CombodomainMouseMoved(evt);
            }
        });
        Combodomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombodomainActionPerformed(evt);
            }
        });

        lblenterprise.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblenterprise.setForeground(new java.awt.Color(153, 153, 153));
        lblenterprise.setText("Enterprise:");

        Comboenterprise.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Comboenterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Health_Ministry", "Education_Ministry", "Defence_Ministry", "Transport_Ministry" }));
        Comboenterprise.setBorder(null);
        Comboenterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Comboenterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ComboenterpriseMouseMoved(evt);
            }
        });
        Comboenterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboenterpriseActionPerformed(evt);
            }
        });

        lbldpt.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lbldpt.setForeground(new java.awt.Color(153, 153, 153));
        lbldpt.setText("Department:");

        Combodpt.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Combodpt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        Combodpt.setBorder(null);
        Combodpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Combodpt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CombodptMouseMoved(evt);
            }
        });
        Combodpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombodptActionPerformed(evt);
            }
        });

        lblorg.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblorg.setForeground(new java.awt.Color(153, 153, 153));
        lblorg.setText("Organisation:");

        Comboorg.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Comboorg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        Comboorg.setBorder(null);
        Comboorg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Comboorg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ComboorgMouseMoved(evt);
            }
        });
        Comboorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboorgActionPerformed(evt);
            }
        });

        lblrole.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        lblrole.setForeground(new java.awt.Color(153, 153, 153));
        lblrole.setText("Role:");

        Comborole.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        Comborole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Admin", "Employee", "President" }));
        Comborole.setBorder(null);
        Comborole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Comborole.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ComboroleMouseMoved(evt);
            }
        });
        Comborole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboroleActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 2)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(reqaccessbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(govtloginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblrole)
                                    .addGap(13, 13, 13)
                                    .addComponent(Comborole, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(55, 55, 55)
                                    .addComponent(lblCombodomain)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Combodomain, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblenterprise)
                                .addGap(13, 13, 13)
                                .addComponent(Comboenterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblorg)
                                .addGap(13, 13, 13)
                                .addComponent(Comboorg, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(lbldpt)
                                .addGap(13, 13, 13)
                                .addComponent(Combodpt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbldivision)))
                        .addGap(12, 12, 12)
                        .addComponent(Combodivision, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn)
                    .addComponent(jLabel5)
                    .addComponent(reqaccessbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comborole, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrole)
                    .addComponent(Combodomain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCombodomain))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblenterprise)
                    .addComponent(Comboenterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comboorg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblorg)
                    .addComponent(lbldpt)
                    .addComponent(Combodpt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combodivision, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldivision))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addComponent(govtloginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void updateOrganisationComboBox() {
        String selectedEnterprise = Comboenterprise.getSelectedItem().toString();
        // Assuming Combodpt is of type JComboBox<String>
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        // Populate Combodpt based on the selected enterprise
        switch (selectedEnterprise) {
            case "Health_Ministry":
                System.out.println("Health_Ministry");
                model.addElement("--Select--");
                model.addElement("Health_Infra");
                model.addElement("Health_R&D");
                model.addElement("Health_RM");
                break;
                
            case "Defense_Ministry":
                model.addElement("--Select--");
                model.addElement("Defense_Infra");
                model.addElement("Defense_R&D");
                model.addElement("Defense_RM");
                break;
                
            case "Education_Ministry":
                model.addElement("--Select--");
                model.addElement("Education_Infra");
                model.addElement("Education_R&D");
                model.addElement("Education_RM");
                break;
                
            case "Transport_Ministry":
                model.addElement("--Select--");
                model.addElement("Transport_Infra");
                model.addElement("Transport_R&D");
                model.addElement("Transport_RM");
                break;
                
              
            // Add more cases for other enterprises if needed

            default:
                // Handle other cases or set default values
                break;
        }

        Comboorg.setModel(model);
    }
    
    private void updateDepartmentComboBox() {
        String selectedEnterprise = Comboorg.getSelectedItem().toString();
        // Assuming Combodpt is of type JComboBox<String>
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        // Populate Combodpt based on the selected enterprise
        switch (selectedEnterprise) {
            case "Health_Infra":
                model.addElement("--Select--");
                model.addElement("Hospital_Building");
                model.addElement("Health_Equipment_Procurement");
              
                break;
                
            case "Health_R&D":
                model.addElement("--Select--");
                model.addElement("Vaccine_Development");
                model.addElement("Health_Equipment_Production");
               
                break;
                
            case "Health_RM":
                model.addElement("--Select--");
                model.addElement("Hospital_Salaries");
                model.addElement("Hospital_Utilities");
                break;
                
            case "Defense_Infra":
                model.addElement("--Select--");
                model.addElement("Military_Building");
                model.addElement("Arms_Procurement");
              
                break;
                
            case "Defense_R&D":
                model.addElement("--Select--");
                model.addElement("Arms_Development");
                model.addElement("Arms_Production");
               
                break;
                
            case "Defense_RM":
                model.addElement("--Select--");
                model.addElement("Defense_Salaries");
                model.addElement("Defense_Utilities");
                break;
                
                
            case "Education_Infra":
                model.addElement("--Select--");
                model.addElement("School_Building");
                model.addElement("School_Equipment_Procurement");
              
                break;
                
            case "Education_R&D":
                model.addElement("--Select--");
                model.addElement("Course_Development");
                model.addElement("Education_Equipment_Production");
               
                break;
                
            case "Education_RM":
                model.addElement("--Select--");
                model.addElement("Education_Salaries");
                model.addElement("Education_Utilities");
                break;
                
                
             case "Transport_Infra":
                model.addElement("--Select--");
                model.addElement("Bus_Building");
                model.addElement("Bus_Procurement");
              
                break;
                
            case "Transport_R&D":
                model.addElement("--Select--");
                model.addElement("Bus_Development");
                model.addElement("Bus_Production");
               
                break;
                
            case "Transport_RM":
                model.addElement("--Select--");
                model.addElement("Transport_Salaries");
                model.addElement("Transport_Utilities");
                break;
                
                
                
            
           
                
              
            // Add more cases for other enterprises if needed

            default:
                // Handle other cases or set default values
                break;
        }

        Combodpt.setModel(model);
    }
     
     private void updateDivisionComboBox() {
        String selectedEnterprise = Combodpt.getSelectedItem().toString();
        // Assuming Combodpt is of type JComboBox<String>
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        // Populate Combodpt based on the selected enterprise
        switch (selectedEnterprise) {
            case "Hospital_Building":
                model.addElement("--Select--");
                model.addElement("Cancer_Buidling");
                model.addElement("Heart_Building");
              
                break;
                
            case "Hospital_Equipment_Procurement":
                model.addElement("--Select--");
                model.addElement("Defibrillators");
                model.addElement("ECG_Machines");
               
                break;
                
             case "Vaccine_Development":
                model.addElement("--Select--");
                model.addElement("Covid");
                model.addElement("Hepatits");
              
                break;
                
            case "Health_Equipment_Production":
                model.addElement("--Select--");
                model.addElement("Defibrillators");
                model.addElement("ECG_Machines");
               
                break;
                
                
             case "Hospital_Salaries":
                model.addElement("--Select--");
                model.addElement("Doctor_Salaries");
                model.addElement("Nurse_Salaries");
              
                break;
                
            case "Hospital_Utilities":
                model.addElement("--Select--");
                model.addElement("Hospital_Fuel");
                model.addElement("Hospital_Gas");
               
                break;
                
            case "Military_Building":
                model.addElement("--Select--");
                model.addElement("Marine_Building");
                model.addElement("Airforce_Building");
                break;
                
            case "Arms_Procurement":
                model.addElement("--Select--");
                model.addElement("Tanks");
                model.addElement("Guns");
              
                break;
                
            case "Arms_Development":
                model.addElement("--Select--");
                model.addElement("Tanks");
                model.addElement("Guns");
                break;
                
            case "Arms_Production":
                model.addElement("--Select--");
                model.addElement("Tanks");
                model.addElement("Guns");
              
                break;
                
            case "Military_Salaries":
                model.addElement("--Select--");
                model.addElement("General_Salaries");
                model.addElement("Corporal_Salaries");
              
                break;
                
            case "Military_Utilities":
                model.addElement("--Select--");
                model.addElement("Military_Fuel");
                model.addElement("Military_Gas");
               
                break;
                
            case "School_Building":
                model.addElement("--Select--");
                model.addElement("School_Building");
                model.addElement("School_PlayGround");
               
                break;
                
            case "School_Equipment_Procurement":
                model.addElement("--Select--");
                model.addElement("Books");
                model.addElement("Online_Courses");
                break;
                
                
            case "Course_Development":
                model.addElement("--Select--");
                model.addElement("Elementary_Course_Development");
                model.addElement("HighSchool_Course_Development");
              
                break;
                
            case "Education_Equipment_Production":
                model.addElement("--Select--");
                model.addElement("Books");
                model.addElement("Uniform");
               
                break;
                
              case "Education_Salaries":
                model.addElement("--Select--");
                model.addElement("Teacher_Salaries");
                model.addElement("Peon_Salaries");
              
                break;
                
            case "Education_Utilities":
                model.addElement("--Select--");
                model.addElement("Education_Fuel");
                model.addElement("Education_Gas");
               
                break;
                
          
                
             case "Bus_Building":
                model.addElement("--Select--");
                model.addElement("Local_Bus");
                model.addElement("City_Bus");
                
                break;
                
            case "Bus_Procurement":
                model.addElement("--Select--");
                model.addElement("Engine_Procurement");
                model.addElement("Wheels_Procurement");
               
                break;
                
            case "Bus_Development":
                model.addElement("--Select--");
                model.addElement("Engine_Development");
                model.addElement("Wheels_Development");
                break;
                
             case "Bus_Salaries":
                model.addElement("--Select--");
                model.addElement("Driver");
                model.addElement("Cleaner");
              
                break;
                
            case "Bus_Utilities":
                model.addElement("--Select--");
                model.addElement("Bus_Gas");
                model.addElement("Bus_Electricity");
               
                break;
           
                
                
            
           
                
              
            // Add more cases for other enterprises if needed

            default:
                // Handle other cases or set default values
                break;
        }

        Combodivision.setModel(model);
    }
    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        
        CitizenLanding citland = new CitizenLanding(mainframe);
        mainframe.setRightComponent(citland);
        GovernmentLanding govtland = new GovernmentLanding(mainframe);
        mainframe.setLeftComponent(govtland);
    }//GEN-LAST:event_backbtnActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void reqaccessbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqaccessbtnActionPerformed
        // TODO add your handling code here:
        
        RequestAccess reqacc = new RequestAccess(mainframe);
        mainframe.setRightComponent(reqacc);
    }//GEN-LAST:event_reqaccessbtnActionPerformed

    private void govtloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_govtloginbtnActionPerformed
        // TODO add your handling code here:
        
        // Validate role selection
//    String selectedRole = Comborole.getSelectedItem().toString();
//    if (selectedRole.equals("--Select--")) {
//        JOptionPane.showMessageDialog(this, "Please select a role.");
//        return;
//    }
//    
//            
//
//    // Validate domain selection
//    String selectedDomain = Combodomain.getSelectedItem().toString();
//    if (selectedDomain.equals("--Select--")) {
//        JOptionPane.showMessageDialog(this, "Please select a domain.");
//        return;
//    }
//
//    // Validate enterprise selection if domain is "enterprise"
//    if (selectedDomain.equals("enterprise")) {
//        String selectedEnterprise = Comboenterprise.getSelectedItem().toString();
//        if (selectedEnterprise.equals("--Select--")) {
//            JOptionPane.showMessageDialog(this, "Please select an enterprise.");
//            return;
//        }
//    }
//
//    // Validate organisation selection if domain is "organisation"
//    if (selectedDomain.equals("organisation")) {
//        String selectedEnterprise = Comboenterprise.getSelectedItem().toString();
//        String selectedOrganisation = Comboorg.getSelectedItem().toString();
//        if (selectedEnterprise.equals("--Select--") || selectedOrganisation.equals("--Select--")) {
//            JOptionPane.showMessageDialog(this, "Please select both enterprise and organisation.");
//            return;
//        }
//    }
//
//    // Validate department selection if domain is "department"
//    if (selectedDomain.equals("department")) {
//        String selectedEnterprise = Comboenterprise.getSelectedItem().toString();
//        String selectedOrganisation = Comboorg.getSelectedItem().toString();
//        String selectedDepartment = Combodpt.getSelectedItem().toString();
//        if (selectedEnterprise.equals("--Select--") || selectedOrganisation.equals("--Select--") || selectedDepartment.equals("--Select--")) {
//            JOptionPane.showMessageDialog(this, "Please select enterprise, organisation, and department.");
//            return;
//        }
//    }
//
//    // Validate division selection if domain is "division"
//    if (selectedDomain.equals("division")) {
//        String selectedEnterprise = Comboenterprise.getSelectedItem().toString();
//        String selectedOrganisation = Comboorg.getSelectedItem().toString();
//        String selectedDepartment = Combodpt.getSelectedItem().toString();
//        String selectedDivision = Combodivision.getSelectedItem().toString();
//        if (selectedEnterprise.equals("--Select--") || selectedOrganisation.equals("--Select--") || selectedDepartment.equals("--Select--") || selectedDivision.equals("--Select--")) {
//            JOptionPane.showMessageDialog(this, "Please select enterprise, organisation, department, and division.");
//            return;
//        }
//    }
        
          try{
            
            Connection connection = (Connection)DatabaseConnection.getConnection();
            String username = txtusername.getText();
            String password = txtpassword.getText();
            String role = (String) Comborole.getSelectedItem();
            String domain = (String) Combodomain.getSelectedItem();
            System.out.println(domain);
            String enterprise = (String) Comboenterprise.getSelectedItem();
            System.out.println(enterprise);
            String organisation = (String) Comboorg.getSelectedItem();
            System.out.println(organisation);
            String department = (String) Combodpt.getSelectedItem();
            System.out.println(department );
            String division = (String) Combodivision.getSelectedItem();
            System.out.println(division);
            
            
          String sql = "SELECT userid, hashedpassword FROM users WHERE username = ? AND role = ? AND domain = ? AND enterprise = ? AND organisation = ? AND department = ? AND division = ?";

            
            PreparedStatement preparedStatement = (PreparedStatement) connection.prepareStatement(sql);
            preparedStatement.setString(1, username);
            preparedStatement.setString(2, role);
            preparedStatement.setString(3, domain);
            preparedStatement.setString(4, enterprise);
            preparedStatement.setString(5, organisation);
            preparedStatement.setString(6, department);
            preparedStatement.setString(7, division);


            ResultSet rs = preparedStatement.executeQuery();
            if (rs.next()) {
                String selectedNUID = rs.getString("userid");
                String hashedPasswordFromDB = rs.getString("hashedpassword");

                createuserprofile userProfile = new createuserprofile();

                if (userProfile.checkPassword(password, hashedPasswordFromDB)) {
                    System.out.println("selectedNUID: " + selectedNUID);
                    
                     JOptionPane.showMessageDialog(this, "User Logged in Successfully");
                     GovernmentLandingJPanel govtland = new GovernmentLandingJPanel(mainframe,Integer.parseInt(selectedNUID));
                     mainframe.setRightComponent(govtland);
                } else {
                    System.out.println("Login failed");
                    JOptionPane.showMessageDialog(this, "Username or password is incorrect");
                    txtusername.setText("");
                    txtpassword.setText("");
                }
            } else {
                System.out.println("User not found");
                JOptionPane.showMessageDialog(this, "Username or password is incorrect");
                txtusername.setText("");
                txtpassword.setText("");
            }

            
            

               // Execute the professor INSERT query
            

           
            
       
             
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
          
        //Username validation
      
        
    }//GEN-LAST:event_govtloginbtnActionPerformed

    private void CombodomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombodomainActionPerformed
        // TODO add your handling code here:
        String selectedRole = Combodomain.getSelectedItem().toString();
        System.out.println(selectedRole);
        
        
        
        

        // Get the selected role and show/hide components accordingly
        switch (selectedRole) {
            case "enterprise" -> {
               
                System.out.println("enterprise");
                Comboenterprise.setVisible(true);
                lblenterprise.setVisible(true);

                Comboorg.setVisible(false);
                lblorg.setVisible(false);
                Combodpt.setVisible(false);
                lbldpt.setVisible(false);
                Combodivision.setVisible(false);
                lbldivision.setVisible(false);
                
            }
            case "organisation" -> {
                
                
               
                Comboenterprise.setVisible(true);
                lblenterprise.setVisible(true);
                Comboorg.setVisible(true);
                lblorg.setVisible(true);
                
                Combodpt.setVisible(false);
                lbldpt.setVisible(false);
                Combodivision.setVisible(false);
                lbldivision.setVisible(false);
                
                updateOrganisationComboBox();
                System.out.println("otg");
            }
            case "department" -> {
                
                Comboenterprise.setVisible(true);
                Comboorg.setVisible(true);
                Combodpt.setVisible(true);
                lblenterprise.setVisible(true);
                lblorg.setVisible(true);
                lbldpt.setVisible(true);
                lbldivision.setVisible(false);
                Combodivision.setVisible(false);
                
                updateDepartmentComboBox();
               
            }
            case "division" -> {
                
                Comboenterprise.setVisible(true);
                Comboorg.setVisible(true);
                Combodpt.setVisible(true);
                Combodivision.setVisible(true);
                lblenterprise.setVisible(true);
                lblorg.setVisible(true);
                lbldpt.setVisible(true);
                lbldivision.setVisible(true);
                updateDivisionComboBox();
                
                
                
            }
            default -> {
            }
        }
    }//GEN-LAST:event_CombodomainActionPerformed

    private void ComboenterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboenterpriseActionPerformed
        // TODO add your handling code here:
         updateOrganisationComboBox();
    }//GEN-LAST:event_ComboenterpriseActionPerformed

    private void ComboroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboroleActionPerformed
        // TODO add your handling code here:
         String selectedRole = Comborole.getSelectedItem().toString();
        if (!selectedRole.equals("President"))
    {
        Combodomain.setVisible(true);
        lblCombodomain.setVisible(true);
    }
    }//GEN-LAST:event_ComboroleActionPerformed

    private void ComboorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboorgActionPerformed
        // TODO add your handling code here:
         updateDepartmentComboBox();
    }//GEN-LAST:event_ComboorgActionPerformed

    private void CombodptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombodptActionPerformed
        // TODO add your handling code here:
        updateDivisionComboBox();
    }//GEN-LAST:event_CombodptActionPerformed

    private void CombodomainMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CombodomainMouseMoved
        // TODO add your handling code here:
        Combodomain.setToolTipText("Select Domain to Move Forward");
    }//GEN-LAST:event_CombodomainMouseMoved

    private void ComboenterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboenterpriseMouseMoved
        // TODO add your handling code here:
        Comboenterprise.setToolTipText("Select Enterprise to Move Forward");
    }//GEN-LAST:event_ComboenterpriseMouseMoved

    private void ComboorgMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboorgMouseMoved
        // TODO add your handling code here:
        Comboorg.setToolTipText("Select Organisation to Move Forward");
    }//GEN-LAST:event_ComboorgMouseMoved

    private void CombodptMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CombodptMouseMoved
        // TODO add your handling code here:
        Combodpt.setToolTipText("Select Department to Move Forward");
    }//GEN-LAST:event_CombodptMouseMoved

    private void CombodivisionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CombodivisionMouseMoved
        // TODO add your handling code here:
        Combodivision.setToolTipText("Select Division to Login");
    }//GEN-LAST:event_CombodivisionMouseMoved

    private void ComboroleMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboroleMouseMoved
        // TODO add your handling code here:
        Comborole.setToolTipText("Select Role First to Login");
    }//GEN-LAST:event_ComboroleMouseMoved

    private void txtusernameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseMoved
        // TODO add your handling code here:
        txtusername.setToolTipText("Enter Username to Login");
    }//GEN-LAST:event_txtusernameMouseMoved

    private void txtpasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseMoved
        // TODO add your handling code here:
        txtpassword.setToolTipText("Enter Password to Login");
    }//GEN-LAST:event_txtpasswordMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combodivision;
    private javax.swing.JComboBox<String> Combodomain;
    private javax.swing.JComboBox<String> Combodpt;
    private javax.swing.JComboBox<String> Comboenterprise;
    private javax.swing.JComboBox<String> Comboorg;
    private javax.swing.JComboBox<String> Comborole;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton govtloginbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCombodomain;
    private javax.swing.JLabel lbldivision;
    private javax.swing.JLabel lbldpt;
    private javax.swing.JLabel lblenterprise;
    private javax.swing.JLabel lblorg;
    private javax.swing.JLabel lblrole;
    private javax.swing.JButton reqaccessbtn;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
