/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Loginmenus;

import logins.LoginAdminJPanel;
import logins.LoginEmployerJPanel;
import logins.LoginProfessorJPanel;
import ui.CreateUserJPanel;
import ui.MainJFrame;

/**
 *
 * @author Abhinav Uni
 */
public class StudentMenu extends javax.swing.JPanel {
    
    MainJFrame mainframe;

    /**
     * Creates new form StudentMenu
     */
    public StudentMenu(MainJFrame mainframe) {
        initComponents();
        
        this.mainframe = mainframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdmin2 = new javax.swing.JButton();
        btnProfessorLogin2 = new javax.swing.JButton();
        Welcome2 = new javax.swing.JLabel();
        SelectLogin2 = new javax.swing.JLabel();
        NewHere2 = new javax.swing.JLabel();
        btnCreateProfile2 = new javax.swing.JButton();
        btnEmployer2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnStudent2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAdmin2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        btnAdmin2.setForeground(new java.awt.Color(102, 102, 102));
        btnAdmin2.setText("Admin");
        btnAdmin2.setBorder(null);
        btnAdmin2.setBorderPainted(false);
        btnAdmin2.setContentAreaFilled(false);
        btnAdmin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin2ActionPerformed(evt);
            }
        });

        btnProfessorLogin2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        btnProfessorLogin2.setForeground(new java.awt.Color(102, 102, 102));
        btnProfessorLogin2.setText("Professor");
        btnProfessorLogin2.setBorder(null);
        btnProfessorLogin2.setBorderPainted(false);
        btnProfessorLogin2.setContentAreaFilled(false);
        btnProfessorLogin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfessorLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorLogin2ActionPerformed(evt);
            }
        });

        Welcome2.setFont(new java.awt.Font("Baskerville Old Face", 1, 21)); // NOI18N
        Welcome2.setForeground(new java.awt.Color(0, 102, 102));
        Welcome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Uni.png"))); // NOI18N

        SelectLogin2.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        SelectLogin2.setForeground(new java.awt.Color(153, 153, 153));
        SelectLogin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectLogin2.setText("Login As:");

        NewHere2.setFont(new java.awt.Font("Segoe UI Variable", 1, 8)); // NOI18N
        NewHere2.setForeground(new java.awt.Color(153, 153, 153));
        NewHere2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewHere2.setText("New here?");

        btnCreateProfile2.setBackground(new java.awt.Color(204, 255, 255));
        btnCreateProfile2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        btnCreateProfile2.setForeground(new java.awt.Color(0, 102, 102));
        btnCreateProfile2.setText("Create Profile");
        btnCreateProfile2.setBorder(null);
        btnCreateProfile2.setBorderPainted(false);
        btnCreateProfile2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateProfile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProfile2ActionPerformed(evt);
            }
        });

        btnEmployer2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        btnEmployer2.setForeground(new java.awt.Color(102, 102, 102));
        btnEmployer2.setText("Employer");
        btnEmployer2.setBorder(null);
        btnEmployer2.setBorderPainted(false);
        btnEmployer2.setContentAreaFilled(false);
        btnEmployer2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployer2ActionPerformed(evt);
            }
        });

        btnStudent2.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        btnStudent2.setText("Student");
        btnStudent2.setBorder(null);
        btnStudent2.setBorderPainted(false);
        btnStudent2.setContentAreaFilled(false);
        btnStudent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudent2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStudent2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdmin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProfessorLogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEmployer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SelectLogin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateProfile2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(Welcome2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NewHere2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Welcome2)
                .addGap(89, 89, 89)
                .addComponent(SelectLogin2)
                .addGap(13, 13, 13)
                .addComponent(btnAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfessorLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnEmployer2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(NewHere2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateProfile2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin2ActionPerformed
        // TODO add your handling code here:

        LoginAdminJPanel adminlogin = new LoginAdminJPanel(mainframe);
        mainframe.setRightComponent(adminlogin);
        AdminMenu adminmenu = new AdminMenu(mainframe);
        mainframe.setLeftComponent(adminmenu);
       
    }//GEN-LAST:event_btnAdmin2ActionPerformed

    private void btnProfessorLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorLogin2ActionPerformed
        // TODO add your handling code here:

        LoginProfessorJPanel professorlogin = new LoginProfessorJPanel(mainframe);
        mainframe.setRightComponent(professorlogin);
        ProfessorMenu profmenu = new ProfessorMenu(mainframe);
        mainframe.setLeftComponent(profmenu);
    }//GEN-LAST:event_btnProfessorLogin2ActionPerformed

    private void btnCreateProfile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProfile2ActionPerformed
        // TODO add your handling code here:

        CreateUserJPanel createprofile = new CreateUserJPanel(mainframe);
        mainframe.setRightComponent(createprofile);
        LoginMenu loginmenu = new LoginMenu(mainframe);
        mainframe.setLeftComponent(loginmenu);
    }//GEN-LAST:event_btnCreateProfile2ActionPerformed

    private void btnStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudent2ActionPerformed

    private void btnEmployer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployer2ActionPerformed
        // TODO add your handling code here:
        
        LoginEmployerJPanel employerlogin = new LoginEmployerJPanel(mainframe);
        mainframe.setRightComponent(employerlogin);
        EmployerMenu empmenu = new EmployerMenu(mainframe);
        mainframe.setLeftComponent(empmenu);
    }//GEN-LAST:event_btnEmployer2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NewHere2;
    private javax.swing.JLabel SelectLogin2;
    private javax.swing.JLabel Welcome2;
    private javax.swing.JButton btnAdmin2;
    private javax.swing.JButton btnCreateProfile2;
    private javax.swing.JButton btnEmployer2;
    private javax.swing.JButton btnProfessorLogin2;
    private javax.swing.JButton btnStudent2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
