/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logins;


import com.mysql.jdbc.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import ui.LandingJPanel;

import ui.MainJFrame;

import Database.DatabaseConnection;
import ProfessorWorkArea.ProfProfileJPanel;
import Loginmenus.LoginMenu;
import ProfessorWorkArea.MyCoursesJPanel;
import ProfessorWorkArea.ProfProfileJPanel;
import StudentWorkArea.StudentLandingJPanel;
import UserProfiles.createuserprofile;
import professormenus.ProfessorWorkAreaMenu;
import ui.CreateProfessorJPanel;



/**
 *
 * @author abhilashkumargorle
 */
public class LoginProfessorJPanel extends javax.swing.JPanel {
    
     private MainJFrame mainframe;
     private String selectedNUID;

    /**
     * Creates new form AdminLoginJPanel
     */
    public LoginProfessorJPanel(MainJFrame mainframe) {
        
        this.mainframe =mainframe;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfessorLogin = new javax.swing.JPanel();
        WelcomeProfessor = new javax.swing.JLabel();
        proflblUsername = new javax.swing.JLabel();
        proflblPassword = new javax.swing.JLabel();
        adminbtnLogin = new javax.swing.JButton();
        proftxtUsername = new javax.swing.JTextField();
        profbtnBack = new javax.swing.JButton();
        profPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        profbtnRegister = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(969, 407));

        ProfessorLogin.setBackground(new java.awt.Color(0, 0, 0));
        ProfessorLogin.setForeground(new java.awt.Color(255, 255, 255));
        ProfessorLogin.setPreferredSize(new java.awt.Dimension(969, 407));

        WelcomeProfessor.setFont(new java.awt.Font("Segoe UI Black", 0, 34)); // NOI18N
        WelcomeProfessor.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeProfessor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeProfessor.setText("Welcome, Professor!");

        proflblUsername.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        proflblUsername.setForeground(new java.awt.Color(153, 153, 153));
        proflblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        proflblUsername.setText("Username :");

        proflblPassword.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        proflblPassword.setForeground(new java.awt.Color(153, 153, 153));
        proflblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        proflblPassword.setText("Password :");

        adminbtnLogin.setBackground(new java.awt.Color(0, 102, 0));
        adminbtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        adminbtnLogin.setText("Login");
        adminbtnLogin.setBorder(null);
        adminbtnLogin.setBorderPainted(false);
        adminbtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtnLoginActionPerformed(evt);
            }
        });

        proftxtUsername.setBackground(new java.awt.Color(0, 0, 0));
        proftxtUsername.setFont(new java.awt.Font("Segoe UI Variable", 1, 21)); // NOI18N
        proftxtUsername.setForeground(new java.awt.Color(255, 255, 255));
        proftxtUsername.setBorder(null);

        profbtnBack.setBackground(new java.awt.Color(0, 0, 0));
        profbtnBack.setForeground(new java.awt.Color(255, 255, 255));
        profbtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back (1).png"))); // NOI18N
        profbtnBack.setText("Back");
        profbtnBack.setBorder(null);
        profbtnBack.setBorderPainted(false);
        profbtnBack.setContentAreaFilled(false);
        profbtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profbtnBackActionPerformed(evt);
            }
        });

        profPassword.setBackground(new java.awt.Color(0, 0, 0));
        profPassword.setFont(new java.awt.Font("Segoe UI Variable", 1, 21)); // NOI18N
        profPassword.setForeground(new java.awt.Color(255, 255, 255));
        profPassword.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("______________________________________________________________________________________________________________________________________________________________________________");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("______________________________________________________________________________________________________________________________________________________________________________");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Professor.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Haven't Registered yet?");

        profbtnRegister.setBackground(new java.awt.Color(204, 255, 255));
        profbtnRegister.setFont(new java.awt.Font("Segoe UI Variable", 1, 13)); // NOI18N
        profbtnRegister.setForeground(new java.awt.Color(0, 102, 102));
        profbtnRegister.setText("Register");
        profbtnRegister.setBorder(null);
        profbtnRegister.setBorderPainted(false);
        profbtnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profbtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profbtnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfessorLoginLayout = new javax.swing.GroupLayout(ProfessorLogin);
        ProfessorLogin.setLayout(ProfessorLoginLayout);
        ProfessorLoginLayout.setHorizontalGroup(
            ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLoginLayout.createSequentialGroup()
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(profbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(WelcomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfessorLoginLayout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(adminbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProfessorLoginLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                                        .addComponent(proflblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(profPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                                        .addComponent(proflblUsername)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(proftxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))))))
                        .addGap(144, 144, 144)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profbtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ProfessorLoginLayout.setVerticalGroup(
            ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLoginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(profbtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addComponent(WelcomeProfessor)
                        .addGap(89, 89, 89)
                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(proftxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proflblUsername))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proflblPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(profPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addComponent(adminbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        ProfessorLoginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {profPassword, profbtnBack});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ProfessorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ProfessorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtnLoginActionPerformed
        // TODO add your handling code here:
           try{
            
            Connection connection = (Connection)DatabaseConnection.getConnection();
            String username = proftxtUsername.getText();
            String password = profPassword.getText();
            
            
           String sql = "SELECT NUID, hashedpassword FROM users WHERE username = ? AND profile_type = 'Professor'";
            
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, username);

            
             
            
            
            
            
            
            ResultSet rs = preparedStatement.executeQuery();
            if (rs.next()) {
                String selectedNUID = rs.getString("NUID");
                String hashedPasswordFromDB = rs.getString("hashedpassword");

                createuserprofile userProfile = new createuserprofile();

                if (userProfile.checkPassword(password, hashedPasswordFromDB)) {
                    System.out.println("selectedNUID: " + selectedNUID);
                    ProfProfileJPanel stulanding = new ProfProfileJPanel(mainframe, selectedNUID);
                    mainframe.setRightComponent(stulanding);
                    ProfessorWorkAreaMenu prof = new ProfessorWorkAreaMenu(mainframe, selectedNUID);
                    mainframe.setLeftComponent(prof);
                    
                } else {
                    System.out.println("Login failed");
                    JOptionPane.showMessageDialog(this, "Username or password is incorrect");
                    proftxtUsername.setText("");
                    profPassword.setText("");
                }
            } else {
                System.out.println("User not found");
                JOptionPane.showMessageDialog(this, "Username or password is incorrect");
                proftxtUsername.setText("");
                profPassword.setText("");
            }

            
            

               // Execute the professor INSERT query
            

           
            
       
             
        }catch(Exception e){
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_adminbtnLoginActionPerformed

    private void profbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profbtnBackActionPerformed
          // TODO add your handling code here:
          
           LandingJPanel landingpanel = new LandingJPanel(mainframe);
           mainframe.setRightComponent(landingpanel);
           LoginMenu loginmenu = new LoginMenu(mainframe);
           mainframe.setLeftComponent(loginmenu);

    }//GEN-LAST:event_profbtnBackActionPerformed

    private void profbtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profbtnRegisterActionPerformed
        // TODO add your handling code here:
        
        CreateProfessorJPanel login = new CreateProfessorJPanel(mainframe);
        mainframe.setRightComponent(login);
    }//GEN-LAST:event_profbtnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProfessorLogin;
    private javax.swing.JLabel WelcomeProfessor;
    private javax.swing.JButton adminbtnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField profPassword;
    private javax.swing.JButton profbtnBack;
    private javax.swing.JButton profbtnRegister;
    private javax.swing.JLabel proflblPassword;
    private javax.swing.JLabel proflblUsername;
    private javax.swing.JTextField proftxtUsername;
    // End of variables declaration//GEN-END:variables
}
